name = "taleve"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Taleve"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Taleve"
